kind: Service
apiVersion: v1
metadata:
  name: fragance-api-service
  labels:
    app: fragance-api
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: fragance-api
  type: ClusterIP
