apiVersion: apps/v1
kind: Deployment
metadata:
  name: fragance-api-deployment
  labels:
    app: fragance-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fragance-api
  template:
    metadata:
      labels:
        app: fragance-api
    spec:
      containers:
      - name: fragance-api-container
        image: adrrf/fraganceapi:latest
        ports:
          - containerPort: 8080
        env:
          - name: MONGO_URI
            value: mongodb://mongodb-service:27017
          - name: MONGO_HOST
            value: mongo
          - name: MONGO_PORT
            value: "27017"
          - name: DB_NAME
            value: fragances
          - name: COLLECTION_NAME
            value: fragances
          - name: MONGO_INITDB_ROOT_USERNAME
            value: fragance
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: fragance
          - name: NODE_ENV
            value: production
          - name: PORT
            value: "8080"
