services:
  mongo:
    image: mongo:latest
    container_name: mongo
    command: ["--logpath", "/var/log/mongodb/db.log"]
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}

  fragance-api:
    image: adrrf/fragance-api:lastest
    container_name: fragance-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-}:8080"
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
      - COLLECTION_NAME=${COLLECTION_NAME}
      - NODE_ENV=production
      - PORT=${PORT}
    depends_on:
      - mongo
